export const UPDATE_QUERY = 'UPDATE_QUERY';
export const ADD_SAVED_QUERY = 'ADD_SAVED_QUERY';
export const DELETE_SAVED_QUERY = 'DELETE_SAVED_QUERY';
export const GET_QUERY_RESPONSE = 'GET_QUERY_RESPONSE';
export const GET_SCHEMA = 'GET_SCHEMA';
