export const UPDATE_QUERY = 'UPDATE_QUERY';
export const ADD_SAVED_QUERY = 'ADD_SAVED_QUERY';
export const DELETE_SAVED_QUERY = 'DELETE_SAVED_QUERY';
export const GET_QUERY_RESPONSE = 'GET_QUERY_RESPONSE';
export const GET_SCHEMA = 'GET_SCHEMA';
export const UPDATE_CURR_RESPONSE = 'UPDATE_CURR_RESPONSE';
export const CREATE_ANAGRAPH = 'CREATE_ANAGRAPH';
export const UPDATE_CURR_ANAGRAPH = 'UPDATE_CURR_ANAGRAPH';
